create table if not exists public.drama_projects (
  id bigint generated by default as identity primary key,
  project_key text not null unique default 'default',
  project jsonb not null,
  updated_at timestamptz not null default now()
);
alter table public.drama_projects enable row level security;
-- Start with no public access. Add authenticated user policies when auth is introduced.
create index if not exists drama_projects_updated_at_idx on public.drama_projects(updated_at desc);