/* v0.4 */
"use client";
import {useEffect,useMemo,useState} from "react";
import type {Episode,Project,Revision,Scene} from "../lib/types";
import {starterProject} from "../lib/starter";
import {loadProject,saveProject} from "../lib/storage";
import {cloudProject} from "../lib/cloud";
import {loadRevisions,restoreRevision,saveRevision} from "../lib/revisions";
import {continuityIssues} from "../lib/continuity";
import {clearAuth,loadAuth} from "../lib/auth";
const tabs=["Dashboard","Characters","Episodes","Script Editor","Writers Room","Relationships","Series Bible","Visual Studio","Export"];
const copy=<T,>(v:T):T=>JSON.parse(JSON.stringify(v));
const makeScene=(id:number):Scene=>({id,heading:"INT. NEW LOCATION - DAY",location:"New Location",time:"DAY",action:"Describe the action.",dialogue:"CHARACTER\nDialogue.",status:"draft",visualPrompt:"Cinematic scene concept."});
export default function Home(){
 const [project,setProject]=useState<Project>(starterProject),[tab,setTab]=useState("Dashboard"),[episodeId,setEpisodeId]=useState(1),[sceneId,setSceneId]=useState(101),[prompt,setPrompt]=useState(""),[output,setOutput]=useState(""),[busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[cloud,setCloud]=useState<"local"|"cloud">("local"),[revisions,setRevisions]=useState<Revision[]>([]),[projects,setProjects]=useState<{key:string;name:string;project:Project}[]>([]),[projectKey,setProjectKey]=useState("midnight-district"),[auth,setAuth]=useState<ReturnType<typeof loadAuth>>(null),[authReady,setAuthReady]=useState(false);
 useEffect(()=>{const p=loadProject(starterProject);setProject(p);setRevisions(loadRevisions());const r=localStorage.getItem("ai-drama-studio-projects-v1");setProjects(r?JSON.parse(r):[{key:"midnight-district",name:p.title,project:p}]);const a=loadAuth();setAuth(a);setAuthReady(true);},[]);
 useEffect(()=>{if(!authReady||!auth)return;cloudProject("load",undefined,projectKey,auth.accessToken).then(r=>{if(r.project){setP(r.project);setCloud(r.cloud?"cloud":"local");setEpisodeId(r.project.episodes[0]?.id||1);setSceneId(r.project.episodes[0]?.scenes[0]?.id||0)}else if(r.authenticated){cloudProject("save",project,projectKey,auth.accessToken).then(x=>setCloud(x.cloud?"cloud":"local")).catch(()=>{})}}).catch(()=>{});},[authReady,auth?.accessToken,projectKey]);
 useEffect(()=>{if(!authReady||!auth)return;const t=setTimeout(()=>{cloudProject("save",project,projectKey,auth.accessToken).then(r=>{if(r.cloud)setCloud("cloud")}).catch(()=>{})},1200);return()=>clearTimeout(t)},[project,projectKey,authReady,auth?.accessToken]);
 useEffect(()=>{if(project)saveProject(project)},[project]);
 const episode=project.episodes.find(e=>e.id===episodeId)||project.episodes[0],scene=episode?.scenes.find(s=>s.id===sceneId)||episode?.scenes[0],issues=useMemo(()=>continuityIssues(project),[project]);
 const setP=(p:Project)=>setProject(copy(p));
 const updateScene=(patch:Partial<Scene>)=>{if(!episode||!scene)return;setP({...project,episodes:project.episodes.map(e=>e.id===episode.id?{...e,scenes:e.scenes.map(s=>s.id===scene.id?{...s,...patch}:s)}:e)});};
 const snapshot=(label:string)=>{saveRevision(project,label);setRevisions(loadRevisions())};
 const addScene=()=>{if(!episode)return;snapshot("Before adding scene");const s=makeScene(Date.now());setP({...project,episodes:project.episodes.map(e=>e.id===episode.id?{...e,scenes:[...e.scenes,s]}:e)});setSceneId(s.id);setTab("Script Editor")};
 const addEpisode=()=>{const id=Math.max(0,...project.episodes.map(e=>e.id))+1,s=makeScene(id*100+1),e:Episode={id,title:"Untitled Episode",status:"Draft",summary:"New episode.",scenes:[s]};setP({...project,episodes:[...project.episodes,e]});setEpisodeId(id);setSceneId(s.id);setTab("Script Editor");snapshot("Before adding episode")};
 async function generate(task:string){setBusy(true);setOutput("");snapshot("Before AI: "+task);try{const r=await fetch("/api/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({task,prompt:prompt||task,context:JSON.stringify({project,episode,scene}),system:"You are the AI Drama Studio writers-room engine. Return production-ready television material. Respect continuity. Be specific and cinematic."})});const d=await r.json();if(!r.ok)throw Error(d.error||"AI unavailable");setOutput(d.text||"No output returned.");setNotice("AI draft generated. Apply it to the selected scene when ready.");}catch(e){setOutput("LOCAL FALLBACK\n\n"+(scene?"Continue this scene: "+scene.heading+"\n\n"+scene.dialogue:"Create the next story beat."));setNotice("Claude is not connected; this is a local fallback draft.");}finally{setBusy(false)}}
 const apply=()=>{if(!scene||!output)return;updateScene({action:scene.action+"\n\n"+output});snapshot("Applied AI draft");setNotice("AI material applied to the selected scene.")};
 async function saveCloud(){try{const r=await cloudProject("save",project,projectKey,auth?.accessToken);setCloud(r.cloud?"cloud":"local");setNotice(r.cloud?"Saved to cloud.":"Saved locally; cloud is not configured.")}catch{setNotice("Cloud save failed; local copy is safe.")}}
 async function loadCloud(){try{const r=await cloudProject("load",undefined,projectKey,auth?.accessToken);if(r.project){setP(r.project);setCloud(r.cloud?"cloud":"local");setNotice(r.cloud?"Loaded cloud project.":"Loaded local/server fallback.")}}catch{setNotice("No cloud project available.")}}
 const saveWorkspace=()=>{const n=[...projects.filter(x=>x.key!==projectKey),{key:projectKey,name:project.title,project}];localStorage.setItem("ai-drama-studio-projects-v1",JSON.stringify(n));setProjects(n);setNotice("Project workspace saved.")};
 const createProject=()=>{const key="project-"+Date.now(),p=copy(starterProject);p.title="Untitled Drama";p.logline="A new series waiting to be written.";const n=[...projects,{key,name:p.title,project:p}];localStorage.setItem("ai-drama-studio-projects-v1",JSON.stringify(n));setProjects(n);setProjectKey(key);setP(p);setTab("Dashboard");setNotice("New project created.")};
 const switchProject=(key:string)=>{const x=projects.find(p=>p.key===key);if(!x)return;setProjectKey(key);setP(x.project);setEpisodeId(x.project.episodes[0]?.id||1);setSceneId(x.project.episodes[0]?.scenes[0]?.id||0);setTab("Dashboard")};
 const restore=(id:string)=>{const p=restoreRevision(id);if(p){setP(p);setRevisions(loadRevisions());setNotice("Revision restored.")}};
 return <main><aside className="sidebar"><div className="brand"><span className="mark">✦</span><div><b>DRAMA</b><small>STUDIO</small></div></div><div className="workspace"><small>WORKSPACE</small><strong>{project.title}</strong><em>SEASON {String(project.season).padStart(2,"0")}</em></div><label className="projectPicker"><small>PROJECT</small><select value={projectKey} onChange={e=>switchProject(e.target.value)}>{projects.map(p=><option key={p.key} value={p.key}>{p.name}</option>)}</select></label><nav>{tabs.map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}><span>{x==="Dashboard"?"⌂":x==="Characters"?"◉":x==="Episodes"?"▣":x==="Script Editor"?"✎":x==="Writers Room"?"✦":x==="Relationships"?"⌘":x==="Series Bible"?"▤":x==="Visual Studio"?"◈":"⇩"}</span>{x}</button>)}</nav><div className="sideBottom"><button onClick={()=>setTab("Export")}>⚙ Settings</button>{auth?.user&&<div className="account"><div className="avatar">{(auth.user.email||"U").slice(0,2).toUpperCase()}</div><div><strong>{auth.user.email||"Signed in"}</strong><button className="signOut" onClick={()=>{clearAuth();setAuth(null);setCloud("local");setNotice("Signed out. Local projects remain available.")}}>Sign out</button></div></div>}</div></aside><section className="content"><header><div><p className="eyebrow">SEASON {String(project.season).padStart(2,"0")} / {tab.toUpperCase()}</p><h1>{tab==="Dashboard"?"Your story is taking shape.":tab}</h1></div><div className="actions"><span className={"cloudBadge "+cloud}>● {auth?.user?(cloud==="cloud"?"Cloud synced":"Account"):"Local"}</span><button className="ghost" onClick={saveCloud}>Save</button><button className="primary" onClick={()=>generate("Write the next compelling scene.")} disabled={busy}>{busy?"Thinking…":"✦ Generate"}</button></div></header>{notice&&<div className="notice">{notice}<button onClick={()=>setNotice("")}>×</button></div>}{tab==="Dashboard"&&<Dashboard project={project} issues={issues} setTab={setTab}/>} {tab==="Characters"&&<Characters project={project} setProject={setP}/>} {tab==="Episodes"&&<Episodes project={project} setEpisodeId={setEpisodeId} setSceneId={setSceneId} setTab={setTab} addEpisode={addEpisode}/>} {tab==="Script Editor"&&<Editor project={project} episode={episode} scene={scene} setEpisodeId={setEpisodeId} setSceneId={setSceneId} updateScene={updateScene} addScene={addScene}/>} {tab==="Writers Room"&&<Writers prompt={prompt} setPrompt={setPrompt} output={output} busy={busy} generate={generate} apply={apply}/>} {tab==="Relationships"&&<Relationships project={project}/>} {tab==="Series Bible"&&<Bible project={project} setProject={setP}/>} {tab==="Visual Studio"&&<Visual project={project} setTab={setTab} setEpisodeId={setEpisodeId} setSceneId={setSceneId}/>} {tab==="Export"&&<Export project={project} issues={issues} revisions={revisions} restore={restore} saveWorkspace={saveWorkspace} createProject={createProject} loadCloud={loadCloud} saveCloud={saveCloud}/>}</section></main>}
function Dashboard({project,issues,setTab}:{project:Project;issues:string[];setTab:(x:string)=>void}){const words=project.episodes.reduce((n,e)=>n+e.scenes.reduce((a,s)=>a+s.action.split(/\s+/).filter(Boolean).length+s.dialogue.split(/\s+/).filter(Boolean).length,0),0);return <><section className="hero"><div><span className="pill">IN PRODUCTION</span><h2>{project.title}</h2><p>{project.logline}</p><div className="heroBtns"><button className="primary" onClick={()=>setTab("Writers Room")}>Continue writing ✦</button><button className="ghost" onClick={()=>setTab("Series Bible")}>Open series bible</button></div></div><div className="heroArt"><div className="moon">☾</div><div className="city">▰ ▰ ▰ ▰</div></div></section><div className="stats"><Stat n={project.episodes.length} l="EPISODES" s="in production"/><Stat n={project.characters.length} l="CHARACTERS" s="with profiles"/><Stat n={words} l="SCRIPT WORDS" s="across scenes"/><Stat n={issues.length} l="CONTINUITY" s={issues.length?"review needed":"clean"}/></div><div className="grid2"><section className="panel"><Head t="EPISODE PIPELINE" h="Latest episodes" a="View all" on={()=>setTab("Episodes")}/>{project.episodes.map(e=><div className="row" key={e.id}><b>{String(e.id).padStart(2,"0")}</b><div><strong>{e.title}</strong><p>{e.summary}</p></div><span className="status">{e.status}</span></div>)}</section><section className="panel"><Head t="AI PRODUCTION" h="Studio health"/><div className="health"><b>{issues.length?"Review needed":"All systems clear"}</b><p>{issues.length?issues[0]:"Characters, scenes and story bible are aligned."}</p></div><div className="miniList"><span>✦ Claude writers room</span><span>◈ Visual prompts</span><span>⌘ Continuity engine</span></div></section></div></>}
function Stat({n,l,s}:{n:number|string;l:string;s:string}){return <div><small>{l}</small><b>{n}</b><span>{s}</span></div>}
function Head({t,h,a,on}:{t:string;h:string;a?:string;on?:()=>void}){return <div className="panelHead"><div><small>{t}</small><h3>{h}</h3></div>{a&&<button onClick={on} className="ghost small">{a} →</button>}</div>}
function Characters({project,setProject}:{project:Project;setProject:(p:Project)=>void}){const add=()=>setProject({...project,characters:[...project.characters,{id:Date.now(),name:"New Character",role:"Supporting",trait:"Complex",bio:"Add the character history.",wants:"",secret:""}]});return <div className="workspaceGrid"><section className="panel"><Head t="CAST" h={project.characters.length+" characters"} a="+ New" on={add}/>{project.characters.map(c=><div className="characterRow" key={c.id}><div className="portrait">{c.name.split(" ").map(x=>x[0]).join("")}</div><div><strong>{c.name}</strong><p>{c.role} · {c.trait}</p></div></div>)}</section><section className="panel editor"><small>CHARACTER PROFILES</small>{project.characters.map(c=><div className="profile" key={c.id}><h3>{c.name}</h3><label>Name<input value={c.name} onChange={e=>setProject({...project,characters:project.characters.map(x=>x.id===c.id?{...x,name:e.target.value}:x)})}/></label><div className="two"><label>Role<input value={c.role} onChange={e=>setProject({...project,characters:project.characters.map(x=>x.id===c.id?{...x,role:e.target.value}:x)})}/></label><label>Core trait<input value={c.trait} onChange={e=>setProject({...project,characters:project.characters.map(x=>x.id===c.id?{...x,trait:e.target.value}:x)})}/></label></div><label>Biography<textarea value={c.bio} onChange={e=>setProject({...project,characters:project.characters.map(x=>x.id===c.id?{...x,bio:e.target.value}:x)})}/></label></div>)}</section></div>}
function Episodes({project,setEpisodeId,setSceneId,setTab,addEpisode}:{project:Project;setEpisodeId:(x:number)=>void;setSceneId:(x:number)=>void;setTab:(x:string)=>void;addEpisode:()=>void}){return <section className="panel"><Head t={"SEASON "+project.season} h="Episode board" a="+ New episode" on={addEpisode}/>{project.episodes.map(e=><button className="episodeCard" key={e.id} onClick={()=>{setEpisodeId(e.id);setSceneId(e.scenes[0]?.id||0);setTab("Script Editor")}}><b>{String(e.id).padStart(2,"0")}</b><div><h3>{e.title}</h3><p>{e.summary}</p></div><span className="status">{e.status}</span></button>)}</section>}
function Editor({project,episode,scene,setEpisodeId,setSceneId,updateScene,addScene}:{project:Project;episode?:Episode;scene?:Scene;setEpisodeId:(x:number)=>void;setSceneId:(x:number)=>void;updateScene:(p:Partial<Scene>)=>void;addScene:()=>void}){return <div className="scriptGrid"><section className="panel sceneList"><Head t="EPISODES" h="Scene list"/>{project.episodes.map(e=><div key={e.id}><button className="episodePick" onClick={()=>{setEpisodeId(e.id);setSceneId(e.scenes[0]?.id||0)}}>{String(e.id).padStart(2,"0")} · {e.title}</button>{e.id===episode?.id&&e.scenes.map(s=><button className={"scenePick "+(scene?.id===s.id?"selected":"")} key={s.id} onClick={()=>setSceneId(s.id)}>{s.heading}</button>)}</div>)}<button className="ghost full" onClick={addScene}>+ Add scene</button></section><section className="panel editor">{scene?<><div className="scriptToolbar"><span>SCREENPLAY / {episode?.title}</span><span>Scene {scene.id} · AUTOSAVED</span></div><input className="sceneHeading" value={scene.heading} onChange={e=>updateScene({heading:e.target.value})}/><div className="two"><label>Location<input value={scene.location} onChange={e=>updateScene({location:e.target.value})}/></label><label>Time<input value={scene.time} onChange={e=>updateScene({time:e.target.value})}/></label></div><label>Action<textarea className="scriptArea" value={scene.action} onChange={e=>updateScene({action:e.target.value})}/></label><label>Dialogue<textarea className="dialogueArea" value={scene.dialogue} onChange={e=>updateScene({dialogue:e.target.value})}/></label><label>Visual prompt<textarea value={scene.visualPrompt} onChange={e=>updateScene({visualPrompt:e.target.value})}/></label></>:<div className="empty">Select a scene to start writing.</div>}</section></div>}
function Writers({prompt,setPrompt,output,busy,generate,apply}:{prompt:string;setPrompt:(x:string)=>void;output:string;busy:boolean;generate:(x:string)=>void;apply:()=>void}){return <div className="writers"><section className="panel promptPanel"><small>AI WRITERS ROOM</small><h2>Build the next beat.</h2><p>Give Claude a task and the complete series context travels with it.</p><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="e.g. Rewrite the selected scene with sharper dialogue and higher emotional stakes."/><div className="quick"><button onClick={()=>generate("Outline the next episode with 6 escalating scenes.")}>Outline episode</button><button onClick={()=>generate("Rewrite the selected scene with sharper dialogue.")}>Rewrite scene</button><button onClick={()=>generate("Continue the selected scene for the next beat.")}>Continue scene</button><button onClick={()=>generate("Check the story for continuity risks and concrete fixes.")}>Continuity check</button></div><button className="primary generate" onClick={()=>generate(prompt||"Develop production-ready story material.")} disabled={busy}>{busy?"Claude is writing…":"✦ Generate with Claude"}</button></section><section className="panel output"><small>GENERATED MATERIAL</small><h3>{output?"Draft ready":"Waiting for a writers-room pass"}</h3>{output?<><pre>{output}</pre><button className="primary" onClick={apply}>Apply to selected scene</button></>:<div className="empty">Your next scene, outline, rewrite or continuity pass will appear here.</div>}</section></div>}
function Relationships({project}:{project:Project}){return <section className="panel"><Head t="CHARACTER DYNAMICS" h="Relationship map"/><div className="relationshipGrid">{project.relationships.map(r=>{const a=project.characters.find(c=>c.id===r.from),b=project.characters.find(c=>c.id===r.to);return <div className="relationship" key={r.id}><div className="relationNames"><b>{a?.name}</b><span>↔</span><b>{b?.name}</b></div><strong>{r.type}</strong><div className="bar"><i style={{width:r.strength+"%"}}/></div><p>{r.note}</p></div>})}</div></section>}
function Bible({project,setProject}:{project:Project;setProject:(p:Project)=>void}){return <section className="panel bible"><small>SERIES BIBLE</small><h2>{project.title}</h2><label>Logline<textarea value={project.logline} onChange={e=>setProject({...project,logline:e.target.value})}/></label><label>World & continuity<textarea className="large" value={project.bible} onChange={e=>setProject({...project,bible:e.target.value})}/></label></section>}
function Visual({project,setTab,setEpisodeId,setSceneId}:{project:Project;setTab:(x:string)=>void;setEpisodeId:(x:number)=>void;setSceneId:(x:number)=>void}){return <section className="panel"><Head t="VISUAL DEVELOPMENT" h="Storyboard prompts"/><div className="visualGrid">{project.episodes.flatMap(e=>e.scenes.map(s=><button className="visualCard" key={s.id} onClick={()=>{setEpisodeId(e.id);setSceneId(s.id);setTab("Script Editor")}}><div className="visualImage">◈</div><strong>{s.heading}</strong><p>{s.visualPrompt}</p><span>Open in script →</span></button>))}</div></section>}
function Export({project,issues,revisions,restore,saveWorkspace,createProject,loadCloud,saveCloud}:{project:Project;issues:string[];revisions:Revision[];restore:(id:string)=>void;saveWorkspace:()=>void;createProject:()=>void;loadCloud:()=>void;saveCloud:()=>void}){const download=()=>{const blob=new Blob([JSON.stringify(project,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="ai-drama-studio-project.json";a.click();URL.revokeObjectURL(a.href)};return <div className="grid2"><section className="panel"><small>PROJECT PACKAGE</small><h2>Take the show with you.</h2><p>Export the complete structured project for backup, versioning or future database migration.</p><div className="actions"><button className="primary" onClick={download}>⇩ Export JSON</button><button className="ghost" onClick={saveWorkspace}>Save workspace</button><button className="ghost" onClick={createProject}>New project</button></div><hr/><div className="actions"><button className="primary" onClick={saveCloud}>☁ Save to cloud</button><button className="ghost" onClick={loadCloud}>↻ Load cloud</button></div></section><section className="panel"><small>REVISION HISTORY</small><h3>{revisions.length} snapshots</h3>{revisions.length?revisions.slice(0,12).map(r=><div className="revision" key={r.id}><div><b>{r.label}</b><span>{new Date(r.createdAt).toLocaleString()}</span></div><button className="ghost small" onClick={()=>restore(r.id)}>Restore</button></div>):<div className="empty">Snapshots are created before major AI edits.</div>}<hr/><small>CONTINUITY REPORT</small><h3>{issues.length?issues.length+" items to review":"Continuity clean"}</h3>{issues.slice(0,5).map((x,i)=><p className="issue" key={i}>{x}</p>)}</section></div>}
